-- Minimal dependency-equivalent schema, cross-checked against migrations 0001/0002/0003/0006.
-- Excludes unrelated crawler/ingestion tables. No production schema changes.
CREATE TABLE public.alembic_version(version_num varchar(32) PRIMARY KEY);
INSERT INTO public.alembic_version VALUES ('20260916_0006');
CREATE TABLE public.applications (
 id uuid PRIMARY KEY,name text NOT NULL,package_name text UNIQUE NOT NULL,
 is_active boolean NOT NULL DEFAULT true,language_code text,country_code text);
CREATE TABLE public.categories(id bigint PRIMARY KEY,code text UNIQUE NOT NULL,name text NOT NULL);
CREATE TABLE public.application_categories(application_id uuid NOT NULL REFERENCES applications(id),
 category_id bigint NOT NULL REFERENCES categories(id),is_primary boolean NOT NULL DEFAULT false,
 PRIMARY KEY(application_id,category_id));
CREATE UNIQUE INDEX uq_application_primary_category ON public.application_categories(application_id) WHERE is_primary IS TRUE;
CREATE TABLE public.crawl_tasks(id uuid PRIMARY KEY,application_id uuid NOT NULL REFERENCES applications(id),
 task_type text NOT NULL CHECK(task_type IN('app_details','reviews')),
 status text NOT NULL,language_code text NOT NULL,country_code text NOT NULL);
CREATE TABLE public.playstore_app_snapshots(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 crawl_task_id uuid NOT NULL UNIQUE REFERENCES crawl_tasks(id),application_id uuid NOT NULL REFERENCES applications(id),
 collected_at timestamptz NOT NULL,score double precision NOT NULL CHECK(score BETWEEN 0 AND 5),
 ratings_count bigint NOT NULL CHECK(ratings_count>=0),reviews_count bigint NOT NULL CHECK(reviews_count>=0),
 min_installs bigint NOT NULL CHECK(min_installs>=0),store_updated_on date,version text,
 ad_supported boolean NOT NULL DEFAULT false,source_adapter text NOT NULL DEFAULT 'synthetic');
CREATE TABLE public.reviews(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id uuid NOT NULL REFERENCES applications(id),external_review_id text NOT NULL,
 source_at timestamptz NOT NULL,author_name text NOT NULL,thumbs_up_count bigint NOT NULL DEFAULT 0,
 score smallint NOT NULL CHECK(score BETWEEN 1 AND 5),content text NOT NULL,source_adapter text NOT NULL,
 first_observed_at timestamptz NOT NULL,last_observed_at timestamptz NOT NULL,
 UNIQUE(application_id,external_review_id));
CREATE TABLE public.review_observations(crawl_task_id uuid NOT NULL REFERENCES crawl_tasks(id),
 review_id bigint NOT NULL REFERENCES reviews(id),observed_at timestamptz NOT NULL,
 position smallint NOT NULL,score smallint NOT NULL CHECK(score BETWEEN 1 AND 5),
 thumbs_up_count bigint NOT NULL,source_adapter text NOT NULL,
 PRIMARY KEY(crawl_task_id,review_id));
-- BI dependency subset of migration 20260912_0004; no sensitive values are seeded.
CREATE TABLE public.network_captures(
 id uuid PRIMARY KEY,application_id uuid NOT NULL REFERENCES applications(id),scenario text NOT NULL,
 original_filename text NOT NULL DEFAULT 'PRIVATE',capture_format text NOT NULL DEFAULT 'pcapng',
 content_type text NOT NULL DEFAULT 'application/octet-stream',object_key text NOT NULL DEFAULT 'PRIVATE',
 expected_sha256 text NOT NULL DEFAULT repeat('0',64),verified_sha256 text,
 capture_size_bytes bigint NOT NULL,transfer_file_size_bytes bigint NOT NULL,status text NOT NULL,
 created_at timestamptz NOT NULL,uploaded_at timestamptz,analysis_finished_at timestamptz,
 error_code text,error_message text);
CREATE TABLE public.network_analysis_results(
 capture_id uuid PRIMARY KEY REFERENCES network_captures(id),application_id uuid NOT NULL REFERENCES applications(id),
 package_name text NOT NULL,scenario text NOT NULL,analyzed_at timestamptz NOT NULL,
 verified_sha256 text NOT NULL DEFAULT repeat('0',64),analysis_warnings jsonb NOT NULL DEFAULT '[]',
 quic_versions_seen jsonb,capture_duration_ms double precision NOT NULL,truncated_packet_count bigint NOT NULL,
 analysis_warning_count bigint NOT NULL,direction_metadata_available boolean NOT NULL,
 handshake_observed boolean NOT NULL,tcp_present boolean NOT NULL,quic_present boolean NOT NULL,
 other_udp_present boolean NOT NULL,tcp_rtt_available boolean NOT NULL,
 quic_initial_rtt_available boolean NOT NULL,quic_spin_rtt_available boolean NOT NULL,
 dns_metrics_available boolean NOT NULL,comparison_ready boolean NOT NULL,
 network_bytes_total bigint NOT NULL,ip_transport_header_bytes bigint NOT NULL,
 observed_primary_payload_span_ms double precision,average_network_throughput_mbps double precision,
 effective_file_throughput_mbps double precision,total_transfer_amplification_ratio double precision NOT NULL,
 primary_direction_amplification_ratio double precision,reverse_path_cost_ratio double precision,
 ip_transport_header_overhead_ratio double precision,tcp_byte_share double precision,
 quic_byte_share double precision,other_udp_byte_share double precision,tcp_connection_count bigint,
 tcp_handshake_success_rate double precision,tcp_initial_rtt_avg_ms double precision,
 tcp_initial_rtt_p50_ms double precision,tcp_ack_rtt_p95_ms double precision,
 tcp_retransmission_count bigint,tcp_retransmission_rate double precision,tcp_recovery_tax double precision,
 tcp_receiver_stall_ratio double precision,tcp_reset_rate double precision);
