-- Minimal dependency-equivalent schema, cross-checked against migrations 0001/0002/0003/0006.
-- Excludes unrelated crawler/ingestion tables. No production schema changes.
CREATE TABLE public.alembic_version(version_num varchar(32) PRIMARY KEY);
INSERT INTO public.alembic_version VALUES ('20260916_0006');
CREATE TABLE public.applications (
 id uuid PRIMARY KEY,name text NOT NULL,package_name text UNIQUE NOT NULL,
 is_active boolean NOT NULL DEFAULT true,language_code text,country_code text);
CREATE TABLE public.categories(id bigint PRIMARY KEY,code text UNIQUE NOT NULL,name text NOT NULL);
CREATE TABLE public.application_categories(application_id uuid NOT NULL REFERENCES applications(id),
 category_id bigint NOT NULL REFERENCES categories(id),is_primary boolean NOT NULL DEFAULT false,
 PRIMARY KEY(application_id,category_id));
CREATE UNIQUE INDEX uq_application_primary_category ON public.application_categories(application_id) WHERE is_primary IS TRUE;
CREATE TABLE public.crawl_tasks(id uuid PRIMARY KEY,application_id uuid NOT NULL REFERENCES applications(id),
 task_type text NOT NULL CHECK(task_type IN('app_details','reviews')),
 status text NOT NULL,language_code text NOT NULL,country_code text NOT NULL);
CREATE TABLE public.playstore_app_snapshots(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 crawl_task_id uuid NOT NULL UNIQUE REFERENCES crawl_tasks(id),application_id uuid NOT NULL REFERENCES applications(id),
 collected_at timestamptz NOT NULL,score double precision NOT NULL CHECK(score BETWEEN 0 AND 5),
 ratings_count bigint NOT NULL CHECK(ratings_count>=0),reviews_count bigint NOT NULL CHECK(reviews_count>=0),
 min_installs bigint NOT NULL CHECK(min_installs>=0),store_updated_on date,version text,
 ad_supported boolean NOT NULL DEFAULT false,source_adapter text NOT NULL DEFAULT 'synthetic');
CREATE TABLE public.reviews(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id uuid NOT NULL REFERENCES applications(id),external_review_id text NOT NULL,
 source_at timestamptz NOT NULL,author_name text NOT NULL,thumbs_up_count bigint NOT NULL DEFAULT 0,
 score smallint NOT NULL CHECK(score BETWEEN 1 AND 5),content text NOT NULL,source_adapter text NOT NULL,
 first_observed_at timestamptz NOT NULL,last_observed_at timestamptz NOT NULL,
 UNIQUE(application_id,external_review_id));
CREATE TABLE public.review_observations(crawl_task_id uuid NOT NULL REFERENCES crawl_tasks(id),
 review_id bigint NOT NULL REFERENCES reviews(id),observed_at timestamptz NOT NULL,
 position smallint NOT NULL,score smallint NOT NULL CHECK(score BETWEEN 1 AND 5),
 thumbs_up_count bigint NOT NULL,source_adapter text NOT NULL,
 PRIMARY KEY(crawl_task_id,review_id));
