from __future__ import annotations

from typing import Protocol


class ProxyLeasePort(Protocol):
    @property
    def proxy_id(self) -> str | None: ...

    @property
    def is_direct(self) -> bool: ...


class ProxyProvider(Protocol):
    def acquire(self, context_id: str) -> ProxyLeasePort: ...

    def rotate(self, lease: ProxyLeasePort, context_id: str) -> ProxyLeasePort: ...

    def record_success(self, lease: ProxyLeasePort) -> None: ...

    def record_failure(self, lease: ProxyLeasePort) -> bool: ...

    def start_cooldown(self, lease: ProxyLeasePort) -> None: ...

    def mark_unhealthy(self, lease: ProxyLeasePort) -> None: ...

    def is_usable(self, lease: ProxyLeasePort) -> bool: ...

    def release(self, lease: ProxyLeasePort) -> None: ...
