"""Column contracts: only these source attributes can be read by the BI role."""

BASE = {
    "alembic_version": ("version_num",),
    "applications": ("id", "name", "package_name", "is_active", "language_code", "country_code"),
    "categories": ("id", "code", "name"),
    "application_categories": ("application_id", "category_id", "is_primary"),
    "crawl_tasks": ("id", "application_id", "task_type", "status", "country_code", "language_code"),
    "playstore_app_snapshots": (
        "id",
        "application_id",
        "crawl_task_id",
        "collected_at",
        "score",
        "ratings_count",
        "reviews_count",
        "min_installs",
        "store_updated_on",
        "version",
        "ad_supported",
        "source_adapter",
    ),
    "reviews": ("id", "application_id", "first_observed_at"),
    "review_observations": ("crawl_task_id", "review_id", "observed_at", "score"),
}
SENTIMENT = {"review_observations": ("sentiment_status", "sentiment_label", "sentiment_language")}
NETWORK = {
    "network_captures": (
        "id",
        "application_id",
        "scenario",
        "capture_size_bytes",
        "transfer_file_size_bytes",
        "status",
        "created_at",
        "uploaded_at",
        "analysis_finished_at",
    ),
    "network_analysis_results": (
        "capture_id",
        "application_id",
        "package_name",
        "scenario",
        "analyzed_at",
        "capture_duration_ms",
        "truncated_packet_count",
        "analysis_warning_count",
        "direction_metadata_available",
        "handshake_observed",
        "tcp_present",
        "quic_present",
        "other_udp_present",
        "tcp_rtt_available",
        "quic_initial_rtt_available",
        "quic_spin_rtt_available",
        "dns_metrics_available",
        "comparison_ready",
        "network_bytes_total",
        "ip_transport_header_bytes",
        "observed_primary_payload_span_ms",
        "average_network_throughput_mbps",
        "effective_file_throughput_mbps",
        "total_transfer_amplification_ratio",
        "primary_direction_amplification_ratio",
        "reverse_path_cost_ratio",
        "ip_transport_header_overhead_ratio",
        "tcp_byte_share",
        "quic_byte_share",
        "other_udp_byte_share",
        "tcp_connection_count",
        "tcp_handshake_success_rate",
        "tcp_initial_rtt_avg_ms",
        "tcp_initial_rtt_p50_ms",
        "tcp_ack_rtt_p95_ms",
        "tcp_retransmission_count",
        "tcp_retransmission_rate",
        "tcp_recovery_tax",
        "tcp_receiver_stall_ratio",
        "tcp_reset_rate",
    ),
}
SENSITIVE = {
    "reviews": ("content", "author_name", "external_review_id", "source_at", "thumbs_up_count"),
    "review_observations": (
        "content",
        "source_at",
        "position",
        "thumbs_up_count",
        "source_adapter",
        "sentiment_processed_at",
        "sentiment_attempt_count",
    ),
    "network_captures": (
        "original_filename",
        "object_key",
        "error_message",
        "error_code",
        "expected_sha256",
        "verified_sha256",
    ),
    "network_analysis_results": ("verified_sha256", "analysis_warnings", "quic_versions_seen"),
}
